# Site settings
title: Plato Frugal
email: info@platofrugal.com
author: "Cedric Quintes"
description: > # this means to ignore newlines until "baseurl:"
  A modest meal.
baseurl: "" 
url: "http://platofrugal.com" # the base hostname & protocol for your site
twitter: platofrugal
github:  platofrugal
facebook: platofrugal

image: apple-touch-icon-180x180.png
# Build settings
markdown: kramdown

permalink: pretty
sass:
    sass_dir: bower_components/foundation/scss
    style: compressed

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - bower.json
    - node_modules/*

